default: &defaults
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  name: "HostWise-web"

staging:
  <<: *defaults
  active: true
  enable_frontend_error_catching: true
  frontend_error_catching_path: '/appsignal/javascript'

production:
  <<: *defaults
  active: true
  enable_frontend_error_catching: true
  frontend_error_catching_path: '/appsignal/javascript'
