pool: 50
patio: 10
windows: 10
preset: 100
condo:
  0:
    1:
      cleaning: 50
      linens: 0
      toiletries: 0
    2:
      cleaning: 50
      linens: 0
      toiletries: 0
    3:
      cleaning: 50
      linens: 0
      toiletries: 0
    4:
      cleaning: 50
      linens: 0
      toiletries: 0
    5:
      cleaning: 50
      linens: 0
      toiletries: 0
  1:
    1:
      cleaning: 50
      linens: 0
      toiletries: 0
    2:
      cleaning: 60
      linens: 0
      toiletries: 0
    3:
      cleaning: 65
      linens: 0
      toiletries: 0
    4:
      cleaning: 65
      linens: 0
      toiletries: 0
    5:
      cleaning: 65
      linens: 0
      toiletries: 0
  2:
    1:
      cleaning: 75
      linens: 0
      toiletries: 0
    2:
      cleaning: 80
      linens: 0
      toiletries: 0
    3: 
      cleaning: 00
      linens: 0
      toiletries: 0
    4:
      cleaning: 100
      linens: 0
      toiletries: 0
    5:
      cleaning: 100
      linens: 0
      toiletries: 0
  3:
    1:
      cleaning: 100
      linens: 0
      toiletries: 0
    2:
      cleaning: 105
      linens: 0
      toiletries: 0
    3:
      cleaning: 130
      linens: 0
      toiletries: 0
    4:
      cleaning: 150
      linens: 0
      toiletries: 0
    5:
      cleaning: 175
      linens: 0
      toiletries: 0
  4:
    2:
      cleaning: 160
      linens: 0
      toiletries: 0
    3:
      cleaning: 190
      linens: 0
      toiletries: 0
    4:
      cleaning: 200
      linens: 0
      toiletries: 0
    5:
      cleaning: 200
      linens: 0
      toiletries: 0
  5:
    2:
      cleaning: 200
      linens: 0
      toiletries: 0
    3:
      cleaning: 200
      linens: 0
      toiletries: 0
    4:
      cleaning: 225
      linens: 0
      toiletries: 0
    5:
      cleaning: 250
      linens: 0
      toiletries: 0
    6:
      cleaning: 275
      linens: 0
      toiletries: 0
    7:
      cleaning: 300
      linens: 0
      toiletries: 0
  6:
    3:
      cleaning: 275
      linens: 0
      toiletries: 0
    4:
      cleaning: 300
      linens: 0
      toiletries: 0
    5:
      cleaning: 325
      linens: 0
      toiletries: 0
    6:
      cleaning: 350
      linens: 0
      toiletries: 0
    7:
      cleaning: 375
      linens: 0
      toiletries: 0
  7:
    4:
      cleaning: 400
      linens: 0
      toiletries: 0
    5:
      cleaning: 425
      linens: 0
      toiletries: 0
    6:
      cleaning: 450
      linens: 0
      toiletries: 0
    7:
      cleaning: 475
      linens: 0
      toiletries: 0
    8:
      cleaning: 500
      linens: 0
      toiletries: 0
    9:
      cleaning: 525
      linens: 0
      toiletries: 0
    10:
      cleaning: 550
      linens: 0
      toiletries: 0
  8:
    6:
      cleaning: 575
      linens: 0
      toiletries: 0
    7:
      cleaning: 600
      linens: 0
      toiletries: 0
    8:
      cleaning: 625
      linens: 0
      toiletries: 0
    9:
      cleaning: 650
      linens: 0
      toiletries: 0
    10:
      cleaning: 675
      linens: 0
      toiletries: 0
  9:
    6:
      cleaning: 700
      linens: 0
      toiletries: 0
    7:
      cleaning: 725
      linens: 0
      toiletries: 0
    8:
      cleaning: 750
      linens: 0
      toiletries: 0
    9:
      cleaning: 775
      linens: 0
      toiletries: 0
    10:
      cleaning: 800
      linens: 0
      toiletries: 0
  10:
    6:
      cleaning: 875
      linens: 0
      toiletries: 0
    7:
      cleaning: 900
      linens: 0
      toiletries: 0
    8:
      cleaning: 925
      linens: 0
      toiletries: 0
    9:
      cleaning: 950
      linens: 0
      toiletries: 0
    10:
      cleaning: 975
      linens: 0
      toiletries: 0
house:
  0:
    1:
      cleaning: 50
      linens: 0
      toiletries: 0
    2:
      cleaning: 50
      linens: 0
      toiletries: 0
    3:
      cleaning: 50
      linens: 0
      toiletries: 0
    4:
      cleaning: 50
      linens: 0
      toiletries: 0
    5:
      cleaning: 50
      linens: 0
      toiletries: 0
  1:
    1:
      cleaning: 50
      linens: 0
      toiletries: 0
    2:
      cleaning: 60
      linens: 0
      toiletries: 0
    3:
      cleaning: 85
      linens: 0
      toiletries: 0
    4:
      cleaning: 85
      linens: 0
      toiletries: 0
    5:
      cleaning: 85
      linens: 0
      toiletries: 0
  2:
    1:
      cleaning: 90
      linens: 0
      toiletries: 0
    2:
      cleaning: 100
      linens: 0
      toiletries: 0
    3:
      cleaning: 110
      linens: 0
      toiletries: 0
    4:
      cleaning: 115
      linens: 0
      toiletries: 0
    5:
      cleaning: 115
      linens: 0
      toiletries: 0
  3:
    1:
      cleaning: 115
      linens: 0
      toiletries: 0
    2:
      cleaning: 115
      linens: 0
      toiletries: 0
    3:
      cleaning: 150
      linens: 0
      toiletries: 0
    4:
      cleaning: 150
      linens: 0
      toiletries: 0
    5:
      cleaning: 175
      linens: 0
      toiletries: 0
  4:
    2:
      cleaning: 160
      linens: 0
      toiletries: 0
    3:
      cleaning: 190
      linens: 0
      toiletries: 0
    4:
      cleaning: 200
      linens: 0
      toiletries: 0
    5:
      cleaning: 200
      linens: 0
      toiletries: 0
  5:
    2:
      cleaning: 200
      linens: 0
      toiletries: 0
    3:
      cleaning: 200
      linens: 0
      toiletries: 0
    4:
      cleaning: 225
      linens: 0
      toiletries: 0
    5:
      cleaning: 250
      linens: 0
      toiletries: 0
    6:
      cleaning: 275
      linens: 0
      toiletries: 0
    7:
      cleaning: 300
      linens: 0
      toiletries: 0
  6:
    3:
      cleaning: 275
      linens: 0
      toiletries: 0
    4:
      cleaning: 300
      linens: 0
      toiletries: 0
    5:
      cleaning: 325
      linens: 0
      toiletries: 0
    6:
      cleaning: 350
      linens: 0
      toiletries: 0
    7:
      cleaning: 375
      linens: 0
      toiletries: 0
  7:
    4:
      cleaning: 400
      linens: 0
      toiletries: 0
    5:
      cleaning: 425
      linens: 0
      toiletries: 0
    6:
      cleaning: 450
      linens: 0
      toiletries: 0
    7:
      cleaning: 475
      linens: 0
      toiletries: 0
    8:
      cleaning: 500
      linens: 0
      toiletries: 0
    9:
      cleaning: 525
      linens: 0
      toiletries: 0
    10:
      cleaning: 550
      linens: 0
      toiletries: 0
  8:
    6:
      cleaning: 575
      linens: 0
      toiletries: 0
    7:
      cleaning: 600
      linens: 0
      toiletries: 0
    8:
      cleaning: 625
      linens: 0
      toiletries: 0
    9:
      cleaning: 650
      linens: 0
      toiletries: 0
    10:
      cleaning: 675
      linens: 0
      toiletries: 0
  9:
    6:
      cleaning: 700
      linens: 0
      toiletries: 0
    7:
      cleaning: 725
      linens: 0
      toiletries: 0
    8:
      cleaning: 750
      linens: 0
      toiletries: 0
    9:
      cleaning: 775
      linens: 0
      toiletries: 0
    10:
      cleaning: 800
      linens: 0
      toiletries: 0
  10:
    6:
      cleaning: 875
      linens: 0
      toiletries: 0
    7:
      cleaning: 900
      linens: 0
      toiletries: 0
    8:
      cleaning: 925
      linens: 0
      toiletries: 0
    9:
      cleaning: 950
      linens: 0
      toiletries: 0
    10:
      cleaning: 975
      linens: 0
      toiletries: 0
